// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuupa0XbJmuZD8b_Wx1URtxBfY2ZdV6aA',
    appId: '1:788524645419:web:cb1f2d681b424db196be6e',
    messagingSenderId: '788524645419',
    projectId: 'v-i-v-org',
    authDomain: 'v-i-v-org.firebaseapp.com',
    storageBucket: 'v-i-v-org.appspot.com',
    measurementId: 'G-EPDWLT5H4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIbtl5CnIQfM1LDdz0wf53Iq_ENa44EvY',
    appId: '1:788524645419:android:2f6f98b807603a7f96be6e',
    messagingSenderId: '788524645419',
    projectId: 'v-i-v-org',
    storageBucket: 'v-i-v-org.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3NPq0sLhdlNRTiWBj396Wc5Bz603kofU',
    appId: '1:788524645419:ios:c2e4f3463dc6a8de96be6e',
    messagingSenderId: '788524645419',
    projectId: 'v-i-v-org',
    storageBucket: 'v-i-v-org.appspot.com',
    iosClientId: '788524645419-kne45cht2koqr0or4o9nkilqs88s1kbd.apps.googleusercontent.com',
    iosBundleId: 'com.vivsorg.viv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3NPq0sLhdlNRTiWBj396Wc5Bz603kofU',
    appId: '1:788524645419:ios:70fb0c095ce66ac196be6e',
    messagingSenderId: '788524645419',
    projectId: 'v-i-v-org',
    storageBucket: 'v-i-v-org.appspot.com',
    iosClientId: '788524645419-qmjtkaqn38c20u3a285vgdv5siqtgbgs.apps.googleusercontent.com',
    iosBundleId: 'com.vivsorg.viv.RunnerTests',
  );
}
